README.md

To match what is documented in the public Salesforce doc:
https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.unit_testing_using_jest_create_tests

update forceignore pattern

---

src/lightning-mocks/input/input.js

Add missing functions to Input LWC

---

src/config.js

Coverage option fix

---

src/lightning-mocks/platformResourceLoader/platformResourceLoader.js

Defaulting platformResourceLoader mocks as promise

---

src/lightning-stubs/radioGroup/radioGroup.js

Add variant property to radio-group stub

---

src/lightning-stubs/buttonIcon/buttonIcon.js
src/lightning-stubs/buttonMenu/buttonMenu.js
src/lightning-stubs/checkboxGroup/checkboxGroup.js
src/lightning-stubs/recordEditForm/recordEditForm.js
src/lightning-stubs/recordForm/recordForm.js
src/lightning-stubs/recordViewForm/recordViewForm.js

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/80

Update lightning stubs missing props

---

package.json
yarn.lock

https://github.com/salesforce/sfdx-lwc-jest/network/alert/yarn.lock/js-yaml/closed

Upgrade js-yaml to address security alert

---

package.json
tests/__snapshots__/help.test.js.snap
yarn.lock

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/88

update yargs for security alert

---

src/lightning-stubs/inputField/inputField.js

Add required attribute to lightning input field stub

---

CHANGELOG.md
package.json

* Bump version to `0.6.2`
* Update `CHANGELOG.md`

v0.6.2 release

---

src/utils/shell.js
tests/utils/shell.test.js

Fixes #119
Reference:
https://exploringjs.com/impatient-js/ch_strings.html#converting-to-string

Fix null exit code handling on jest process exit

---

src/lightning-stubs/tree/tree.js

fixes https://github.com/salesforce/sfdx-lwc-jest/issues/125

add selectedItem attribute to lightning:tree

---

src/lightning-stubs/navigation/navigation.js

Related to https://github.com/trailheadapps/lwc-recipes/pull/242

lightning/navigation stub to return Promise to match real API shape

---

package.json
scripts/checkLicenseHeaders.js
src/config.js
src/lightning-stubs/datatableKeyboardMixins/datatableKeyboardMixins.js
src/lightning-stubs/navigation/navigation.js
src/resolver.js
src/utils/project.js
src/utils/shell.js
src/utils/test-runner.js
tests/help.test.js
tests/test-runner.test.js
yarn.lock

dependencies with major updates:
- chalk - https://github.com/chalk/chalk/releases/tag/v3.0.0 https://github.com/chalk/chalk/releases/tag/v4.0.0
- yargs - https://github.com/yargs/yargs/releases/tag/v15.0.0

chore: routine dependency upgrades

---

src/lightning-stubs/datatable/datatable.js

Adds the "columnWidthsMode" attribute

---

package.json
yarn.lock

chore: update jest to v25.5.4

---

src/lightning-stubs/badge/badge.js
src/lightning-stubs/configProvider/configProvider.js
src/lightning-stubs/datatable/datatable.js
src/lightning-stubs/datatableKeyboardMixins/datatableKeyboardMixins.js
src/lightning-stubs/inputField/inputField.js
src/lightning-stubs/menuItem/menuItem.js
src/lightning-stubs/messageService/messageService.js
src/lightning-stubs/navigation/navigation.js
src/lightning-stubs/progressRing/progressRing.html
src/lightning-stubs/progressRing/progressRing.js

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/144

Update stubs for Summer 20

---

README.md

Added a coverage script to the install examples in readme.

Doc: added coverage script to the install examples

---

src/lightning-stubs/inputAddress/inputAddress.js
src/lightning-stubs/inputField/inputField.js
src/lightning-stubs/inputRichText/inputRichText.js
src/lightning-stubs/richTextToolbarButton/richTextToolbarButton.html
src/lightning-stubs/richTextToolbarButton/richTextToolbarButton.js
src/lightning-stubs/richTextToolbarButtonGroup/richTextToolbarButtonGroup.html
src/lightning-stubs/richTextToolbarButtonGroup/richTextToolbarButtonGroup.js
src/lightning-stubs/textarea/textarea.js

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/178

update lightning stubs

---

README.md
src/options/options.js
src/utils/test-runner.js
tests/__snapshots__/help.test.js.snap

Backport the following PRs to make it available in spring21 release
https://github.com/salesforce/sfdx-lwc-jest/pull/188
https://github.com/salesforce/sfdx-lwc-jest/pull/190

(backport)feat: Add new --skipApiVersionCheck flag

---

src/index.js

https://github.com/salesforce/sfdx-lwc-jest#testing-wire-adapters

fix: expose new methods from @salesforce/wire-service-jest-util

---

src/utils/test-runner.js

fix: account for difference in behavior between npm v6 and v7

---

.eslintrc
src/apex-stubs/method/method.js
src/config.js
src/resolver.js

fix: automock apex methods with valid wire adapters

---

package.json
src/config.js
yarn.lock

Prepare master branch for spring23 release by updating lwc release version and API version.
Also updates other dependencies.

chore: update lwc dependency to prepare for spring23

---

src/lightning-stubs/uiGraphQLApi/uiGraphQLApi.js

Cherry picking to Summer23 release

feat: add uiGraphQLApi module (#310)

---

README.md

docs: add info about versions to the README

---

src/lightning-stubs/toastContainer/toastContainer.js

Added a stub for the new [lightning/toastContainer](https://developer.salesforce.com/docs/component-library/bundle/lightning-toast-container/documentation) module.

feat: toastContainer stub

---

.circleci/config.yml
package.json

chore: node v18.18.0

---

src/lightning-stubs/recordPicker/recordPicker.js

Add recordPicker new attributes:
- `disabled`
- `fieldLevelHelp`

feat: update recordPicker stubs with disabled & fieldLevelHelp

---

package.json

New minor version for new Salesforce release.

chore: release v7.1.0
