package.json
yarn.lock

A long time ago (before this repo even existed), we used local file versions for the LWC core resources (engine, transformer, etc). To make that work the dependencies of those local files had to be ported to this projects package.json. When the local files were removed and replaced by npm dependencies, the dependencies were not removed with them. Cleaning that up now.

Remove unnecessary dependencies

---

src/resolver.js
src/utils/__mocks__/project.js
src/utils/project.js

Locally in a Salesforce DX project, customers should reference their custom components with the `c` namespace. The custom namespace in `sfdx-project.json` should be ignored when trying to resolve these custom components in unit tests.

remove custom namespace logic in resolver

---

src/utils/test-runner.js

To mimic the environment when the `jest` executable is invoked directly, set `process.env.NODE_ENV` to 'test' if not already set.

Ensure run with NODE_ENV set to test

---

src/lightning-mocks/input/input.js

this attribute (format-fraction-digits) already works fine in LWC so lets add it into mock file

add formatFractionDigits property to the mock

---

README.md

We need to get rid of this dependency!

update README with deasync workaround

---

src/lightning-stubs/card/card.js

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/57
This was mistakenly removed because `title` is a global html attribute. We need to keep it defined as an `@api` property to prevent a significant amount of console errors when running tests.

add title prop back to card stub

---

src/config.js

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/71

coverage path Windws fix

---

README.md

Removed instructions to update `.forceignore` as new DX projects already have `**/__tests__/**`

Dropped instructions to update .forceignore

---

src/lightning-stubs/uiRecordApi/uiRecordApi.js

Fixes https://github.com/salesforce/sfdx-lwc-jest/issues/79

add implementation to getFieldValue

---

src/lightning-stubs/input/input.js

This PR adds the date-style and time-style attributes to the lightining-input stub

Update to include date-style and time-style attributes

---

package.json
scripts/checkLicenseHeaders.js
yarn.lock

Updated packages: chalk@2.4.2, glob@7.1.5, jest@24.9.0, yargs@14.2.0, eslint@6.6.0, isbinaryfile@4.0.2

chore: upgrade package dependencies

---

src/config.js

This PR properly excludes all the `node_modules/` dependencies from being transformed except the lightning-stubs. On top of fixing large file transformation issues, it also greatly improve the overall performance of the test runner (divide by 3 the test during on the [reciepes](https://github.com/trailheadapps/lwc-recipes) repo).
Fix #107, fix #75.
**Note:** This code change will need to be revisited once npm packages distribute components.

fix: exclude all node_modules except lightning-stubs

---

package.json
src/utils/project.js
yarn.lock

Drastically reduces time taken for tests to run by caching the initial result of getmodulepaths as well as replacing the slow glob package with fast-glob.
One test suite went from taking roughly 5.5 minutes to 20 seconds.
And another from roughly 3 minutes to 16.5 seconds
Fix #161.

Improve test performance by caching module paths

---

README.md

Fixed a reference in documentation to legacy project name (lwc-jest)

doc: Fixed reference to legacy project name (lwc-jest)

---

package.json
src/config.js
yarn.lock

This PR fixes https://github.com/salesforce/sfdx-lwc-jest/issues/172
With the latest LWC including the wire reform, `@salesforce/wire-service-jest-util` >= v2.4.2 along with the `setupFilesAfterEnv` from `@lwc/jest-preset` is required for existing tests for a component using a wire adapter keep passing.
Note: `setupFilesAfterEnv` from `@lwc/jest-preset` is needed for synthetic-shadow also.

fix: include setupFilesAfterEnv in jest config

---

src/lightning-stubs/uiObjectInfoApi/uiObjectInfoApi.js

We recently noticed that there was a missing stub for the getObjectInfos uiObjectInfoApi module.

Add missing stub for getObjectInfos

---

.github/ISSUE_TEMPLATE.md
package.json
src/lightning-stubs/datatableKeyboardMixins/datatableKeyboardMixins.js
src/lightning-stubs/navigation/navigation.js
tests/__snapshots__/help.test.js.snap
yarn.lock

This PR upgrades the `dependencies` and `devDependencies` of this project. It fixes #186 and other packages with known vulnerabilities.
It's important to note that this PR contains breaking changes with Jest [update to v26](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2600). Outside jsdom update, most of the jest breaking changes are corner cases that can easily be fixed. In this regard, I think that it is ok to merge this PR in master and do a major version update. Thoughts?

[Breaking] Upgrade dependencies & devDependencies 

---

README.md
src/options/options.js
src/utils/test-runner.js
tests/__snapshots__/help.test.js.snap

This PR introduces a new advanced flag `--skipApiVersionCheck`. When this flag is passed, sfdx-lwc-jest will not check if the `sfdx-project.json` `sourceApiVersion` field is matching with matching the expected API version.
With this flag, ISV who want to avoid bumping their package API version at a different cadence than Salesforce release can keep their test runner version up-to-date.

feat: Add new --skipApiVersionCheck flag 

---

src/config.js

Instead of hardcoding the expected `jest` bin path, the binary location is retrieved by looking up the package via `require.resolve`.
Fix #155.

fix: Retrieve right binary path even if jest is not hoisted

---

src/lightning-stubs/analyticsWaveApi/analyticsWaveApi.js
src/lightning-stubs/combobox/combobox.js
src/lightning-stubs/datatable/datatable.js
src/lightning-stubs/helptext/helptext.js
src/lightning-stubs/input/input.js
src/lightning-stubs/inputAddress/inputAddress.js
src/lightning-stubs/inputRichText/inputRichText.js
src/lightning-stubs/map/map.js
src/lightning-stubs/messageService/messageService.js
src/lightning-stubs/navigation/navigation.js
src/lightning-stubs/outputField/outputField.js
src/lightning-stubs/quickActionPanel/quickActionPanel.html
src/lightning-stubs/quickActionPanel/quickActionPanel.js
src/lightning-stubs/textarea/textarea.js
src/lightning-stubs/uiAppsApi/uiAppsApi.js
src/lightning-stubs/uiListApi/uiListApi.js
src/lightning-stubs/uiListsApi/uiListsApi.js
src/lightning-stubs/uiObjectInfoApi/uiObjectInfoApi.js
src/lightning-stubs/uiRecordApi/uiRecordApi.js

Update lightning stubs with changes from 232.

chore: update lightning stubs

---

.eslintrc
src/apex-stubs/apex/apex.js
src/apex-stubs/method/method.js
src/resolver.js

This PR modifies the resolver so it automatically mocks apex methods with a valid wire adapter.

fix: automock apex methods with valid wire adapters

---

package.json

I noticed that [the npm page for this package](https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest) doesn't have a link to the Git repo. I assume it's because of how the repository is listed in `package.json`. So I ran `npm init --yes` to autogenerate the `repository`/`bugs`/`homepage` properties.

chore(package): update reference to git repo

---

CHANGELOG.md

Fixes #228.
I also added release notes to the GitHub Releases page for 0.12.4, 0.12.5, and 13.0.0.

docs: add note about GitHub Releases page

---

jest.config.js
src/apex-stubs/method/__tests__/apex-method.test.js
src/apex-stubs/method/method.js

fixes #230 
#208 automocks apex and apexContinuation methods with the correct test wire adapter instead of those provided by the `@lwc/jest-transformer` ([apex](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-transformer/src/transforms/apex-scoped-import.js#L90-L100), [apexContinuation](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-transformer/src/transforms/apex-continuation-scoped-import.js)). However, it does not implement correctly the mocked function that is used when invoking imperatively the apex method (the correct implementation is defined [here](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-transformer/src/transforms/utils.js#L78)).
This PR mocks the implementation of the apex method to return a resolved …

fix: apex automock not returning a resolved promise

---

.eslintrc
src/apex-stubs/method/method.js
src/config.js
src/resolver.js

This reverts commit 0cc034df1ba2f5c8c71f638bb11c0f7e5f23ec27.
Cherrypicks #234 into the summer21 branch.
This PR reverts #210, and #208 (#231 was never included in summer21 branch). They provided functionality to auto mock apex methods.
**Notes:**
- Test authors will need to keep implementing their own apex (+apexContinuation) methods mocks after this PR is merged.
- These changes were added to the summer21 branch with #224.

Revert "fix: automock apex methods with valid wire adapters (#224)"

---

README.md

I don't think we actually keep `prerelease` up to date. Our system seems to be:
- `latest` is whatever is latest in the OSS repo
- `winter22` / `spring22` / etc correspond to official Salesforce releases
Fixes #264

docs: remove prerelease reference from README

---

.circleci/config.yml
package.json

Standardize the naming for our release scripts:
yarn release -> full service release
yarn release:version -> update the version
yarn release:publish -> publish the project

chore: standardize release script

---

.circleci/config.yml

Temporarily remove auto-deploy while we find a solution for W-11138153.
Once W-11138153 is resolved, we can add this workflow back in. In the meantime, manual publish using `yarn release:publish` is sufficient.

fix: temporarily remove auto-deploy

---

package.json
tests/__snapshots__/help.test.js.snap
yarn.lock

Reverts a potential breaking change in the upgrade from jest 27 to jest 29.
Should resolve https://github.com/salesforce/sfdx-lwc-jest/issues/288.
This change will be released as 1.1.4. The new breaking upgrade will be released as a new 2.0.0 release.

fix: revert breaking upgrade to jest version

---

src/lightning-stubs/uiGraphQLApi/uiGraphQLApi.js

The initial emit on `graphql` wire adapters was sending `{ data: { data: undefined, errors: undefined }, errors: undefined }`. It should be ` { data: undefined, errors: undefined }`.

fix: fix initial emit for GraphQL adapters

---

src/lightning-stubs/modalBody/modalBody.html
src/lightning-stubs/modalBody/modalBody.js
src/lightning-stubs/modalFooter/modalFooter.html
src/lightning-stubs/modalFooter/modalFooter.js
src/lightning-stubs/modalHeader/modalHeader.html
src/lightning-stubs/modalHeader/modalHeader.js

test fails when using modal-body, modal-header, modal-footer components
Added stub to prevent test from failing

add stub. modalBody, modalHeader, modalFooter

---

src/lightning-stubs/platformShowToastEvent/platformShowToastEvent.js

When testing a component that fires multiple toast with `platformShowToastEvent` we need to access the toast configuration in tests like this ([full source](https://github.com/trailheadapps/lwc-recipes/blob/b959183e0442eab510f35b5b2a3f7274a40bb9eb/force-app/main/default/lwc/miscToastNotification/__tests__/miscToastNotification.test.js#L66)):
```js
// Mock handler for toast event
const handler = jest.fn();
// Add event listener to catch toast event
element.addEventListener(ShowToastEventName, handler);
// Some test logic
// Testing fired event
expect(handler).toHaveBeenCalled();
expect(handler.mock.calls[0][0].detail.title).toBe(TOAST_TITLE);
expect(handler.mock.calls[0][0].detail.message).toBe(TOAST_MESSAGE);
expect(handler.mock.calls[0][0].detail.variant).toBe(TOAST_VARIANT);
```
The …

feat: add toast details in platformShowToastEvent stub

---

src/lightning-stubs/uiRelatedListApi/uiRelatedListApi.js

Added the 6 missing [uiRelatedListApi](https://developer.salesforce.com/docs/platform/lwc/guide/reference-lightning-ui-api-related-list.html) stubs:
- getRelatedListCount
- getRelatedListInfo
- getRelatedListInfoBatch
- getRelatedListRecords
- getRelatedListRecordsBatch
- getRelatedListsInfo
Fixes: #278

feat: added uiRelatedListApi stubs

---

package.json
src/config.js
src/log.js
tests/__snapshots__/help.test.js.snap
tests/config.test.js
yarn.lock

BREAKING CHANGE: Jest updated from v27 to v28
Fixes #319
Updates all dependencies, including Jest. Users of `sfdx-lwc-jest` may need to modify their tests to deal with breaking changes in [Jest 28](https://jestjs.io/docs/28.x/upgrading-to-jest28) and [Jest 29](https://jestjs.io/docs/upgrading-to-jest29).

fix: update dependencies, including jest

---

src/config.js

Cherry-picked from the `spring24` branch.

chore: update expectedApiVersion to 60

---

.github/workflows/unit.yml
package.json
yarn.lock

BREAKING CHANGE: This is _technically_ a breaking change because we are bumping the `@lwc/jest-*` dependencies to [v15](https://github.com/salesforce/lwc-test/releases/tag/v15.0.0), which means that snapshots may change.
We can do a major version bump as a heads-up.

chore: update dependencies

---

package.json
src/config.js

This will be the `summer24` release since all the LWC deps are now up to date.

chore: release v5.0.0

---

src/config.js

[TypeScript is supported by `@lwc/jest-preset`](https://github.com/salesforce/lwc-test/blob/5b1d20c177c33d5faf7135aa133f3c4a3856b0fa/packages/%40lwc/jest-preset/jest-preset.js#L11-L15), but not by `sfdx-lwc-jest`, even though `sfdx-lwc-jest` builds on `@lwc/jest-preset`.
https://github.com/salesforce/sfdx-lwc-jest/blob/c3ace89953103ce603fa3c620194d71d16cd05f8/src/config.js#L32-L36
This PR updates the config provided by `sfdx-lwc-jest` to support TypeScript by using more of `@lwc/jest-preset`.

feat(config): add better support for TypeScript

---

README.md
src/config.js
src/log.js
src/options/options.js
src/utils/__mocks__/project.js
src/utils/test-runner.js
tests/__snapshots__/help.test.js.snap

Following our discussion in #349, I'm proposing to remove the dependency on Salesforce source API version.
This means removing the API version check and deprecating the `--skipApiVersionCheck` flag.
I've kept the flag in order to guarantee backward compatibility and not introduce a breaking change.
If the flag is present, the runner will ignore it and display this warning:
> The --skipApiVersionCheck flag is deprecated and will be removed in future versions.

feat: remove Salesforce source API version dependency

---

.github/dependabot.yml

These deps can't be updated independently; they all depend on each other.

chore(dependabot): group lwc/lwc-test deps together

---

package.json

* Removed the Salesforce source API version dependency.
* The `--skipApiVersion` flag is now deprecated, and has no functionality.
* Added a stub to support the `lightning/platformWorkspaceApi` module.
* Updated the default jest config to inherit from `@lwc/jest-preset`.
* TypeScript files should now be supported without additional configuration.

chore: release v5.1.0

---

package.json

Bumping major since LWC major version has been bumped.
This will be the version for `winter25`.

chore: release v6.0.0

---

src/lightning-stubs/fileUpload/fileUpload.js

Added the required attributes to the fileUpload stub, Teams are blocked on this and require us to update the stub as we are the owner of the component.

Added required attritbutes to the file upload stub

---

src/options/options.js
src/utils/test-runner.js
tests/__snapshots__/help.test.js.snap

The PR fixes an issue #415 where `skipApiVersionCheck` flag deprecation warning would always show up even when the flag was not set because of the default flag value.
I removed the default value and change the check so that the warning only shows up when the flag is set regardless of its value.

fix: skipApiVersionCheck flag deprecation warning

---

.github/workflows/unit.yml

#453 and #454 are failing because of `engines` checks

chore(ci): use latest node v20 in GitHub Actions
